config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  get 'posts/index'
  get 'posts/new'
  post 'posts/create'
  get 'posts/show/:id' => "posts#show"
  get 'posts/edit/:id' => "posts#edit"
  post 'posts/update/:id' => "posts#update"
  get 'posts/destroy/:id' => "posts#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # skip_before_action :verify_authenticity_token
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
  def new
  end

  def create
    @post = Post.new
    
    @post.title = params[:title]
    @post.content = params[:content]
    @post.user_email = current_user.email
    
    @post.save
    
    redirect_to "/posts/index"
  end

  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    post = Post.find(params[:id])
    
    post.title = params[:title]
    post.content = params[:content]
    
    post.save
    
    redirect_to "/posts/index"
  end
  
  def destroy
    @post = Post.find(params[:id])
    
    @post.destroy
    
    redirect_to "/posts/index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudExamApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<form action="/posts/update/<%= @post.id %>" method="POST">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type="text" name="title" value="<%= @post.title %>">
    <textarea name="content"> <%= @post.content %> </textarea>
    <button type="submit">제출</button>
</form>

app/views/posts/index.html.erb
<% if user_signed_in? %>
    <%= current_user.email %> 님 안녕하세요.
    <a href="/users/sign_out" data-method="delete">로그아웃</a>
<% else %>
    <a href="/users/sign_in">로그인</a>
<% end %>
<hr>

<% @posts.each do |post| %>
    title : <%= post.title %>
    content : <%= post.content %>
    <a href="/posts/show/<%= post.id %>">보기</a>
    <a href="/posts/edit/<%= post.id %>">수정</a>
    <a href="/posts/destroy/<%= post.id %>">삭제</a>
    <hr>
<% end %>

<a href="<%= posts_new_path %>">글 작성하러 가기</a>

app/views/posts/new.html.erb
<form action="/posts/create" method="POST">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type="text" name="title">
    <textarea name="content"></textarea>
    <button type="submit">제출</button>
</form>

app/views/posts/show.html.erb
<%= @post.id %> 의 글
<hr>
title : <%= @post.title %>
<hr>
content : <%= @post.content %>
<hr>
email : <%= @post.user_email %>
<hr>
<a href="/posts/index">리스트로 이동</a>